spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/txlcn?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    hikari:
      connectionTimeout: 1000
      validationTimeout: 1000
      maximum-pool-size: 20
      minimum-idle: 0
